name: Update Release Info

on:
  workflow_call:
  workflow_dispatch:

concurrency: release-info

env:
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "22.12.0"

jobs:
  release-info:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ inputs.registry-url }}

      - name: Enable Corepack
        run: |
          corepack enable
          yarn config set enableGlobalCache false

      - name: Load cached dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Build the release-info action
        run: yarn workspace @kitten-science/action-release-info tsc --build

      - name: Generate release information
        id: release-info
        uses: ./packages/action-release-info
        with:
          filename: release-info.json
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::022327457572:role/kitten-science-us0-maintainer
          role-session-name: GitHubActions

      - name: Grab Kitten Scientists Artifacts
        run: |
          curl --location --silent "${{ steps.release-info.outputs.dev-url-default }}" --output dev.js
          curl --location --silent "${{ steps.release-info.outputs.nightly-url-default }}" --output nightly.js
          curl --location --silent "${{ steps.release-info.outputs.stable-url-default }}" --output stable.js

      - name: Deploy to S3
        run: |
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key v2.0.0-beta.8/release-info.json \
            --cache-control "public, s-maxage=3600" \
            --content-type "application/json" \
            --body release-info.json
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key main/release-info.json \
            --cache-control "public, s-maxage=3600" \
            --content-type "application/json" \
            --body release-info.json

          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key v2.0.0-beta.8/dev.js \
            --cache-control "public, s-maxage=600" \
            --content-type "text/javascript" \
            --body dev.js
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key v2.0.0-beta.8/nightly.js \
            --cache-control "public, s-maxage=3600" \
            --content-type "text/javascript" \
            --body nightly.js
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key v2.0.0-beta.8/stable.js \
            --cache-control "public, s-maxage=604800" \
            --content-type "text/javascript" \
            --body stable.js

          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key main/dev.js \
            --cache-control "public, s-maxage=600" \
            --content-type "text/javascript" \
            --body dev.js
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key main/nightly.js \
            --cache-control "public, s-maxage=3600" \
            --content-type "text/javascript" \
            --body nightly.js
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key main/stable.js \
            --cache-control "public, s-maxage=604800" \
            --content-type "text/javascript" \
            --body stable.js
