name: QA

on:
  pull_request:
  push:

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Validate commit messages
        uses: oliversalzburg/action-commit-validator@3d55a588a712a905f073a6a6b1cdeb7af8a37c41 # v0.0.10
        if: github.event_name == 'pull_request'
        with:
          accept_breaking_changes: false
          accept_emoji: false
          accepted_scopes: |
            bonfire
            religion
            science
            space
            time
            trade
            village
            workshop

            api
            build
            container
            core
            deps
            deps-dev
            filters
            i18n
            schema
            settings
            ui
          accepted_types: |
            chore
            ci
            docs
            feat
            fix
            refactor
            test
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.14.0"
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install --immutable

      - run: yarn build:all
      - run: yarn lint:all
      - run: yarn test:all
      - run: yarn kitten-scientists:build
